### ISSUE TITLE
 Which version of MacOS do you use?

### ISSUE THREAD

**Issue by douglashsilva** [matricci/ideapad330-Hackintosh#1]

**Comment by matricci** [comment]
Catalina, I had used up to 10.15.2, without major issues. It can run smoothly IOS emulator, XCode, VSCode, and so on.

**Comment by douglashsilva** [comment]
Talking to the Administrator (MaLd0n) of the Olarila Forum he helped me, I am using a useful version of Catalina 10.15.5 with everything working, according.

I'll attach my EFI, who knows, maybe it helps you. :)

[EFI - ideapad 330 - Catalina 10.15.5 - 2020.zip](https://github.com/matricci/ideapad330-Hackintosh/files/4741548/EFI.-.ideapad.330.-.Catalina.10.15.5.-.2020.zip)

**Comment by matricci** [comment]
Thanks, I will try my Hackintosh as soon as I can. I'm currently using Fedora as my main OS.

**Comment by ghost** [comment]
你好我是一个中国用户，很高兴用到你的efi而且我感觉也很好用，大部分都驱动了，不过AMD显卡我找了很多办法也是没法驱动。有没有兴趣一起讨论一下

**Comment by ghost** [comment]
> 在与奥拉里拉论坛的管理员（MaLd0n）交谈时，他帮助我，我使用的是Catalina 10.15.5的有用版本，一切都在起作用。
> 
> 我会附上我的EFI，谁知道，也许它可以帮助你。:)
> 
> [EFI - 创意板 330 - 卡塔利娜 10.15.5 - 2020.zip](https://github.com/matricci/ideapad330-Hackintosh/files/4741548/EFI.-.ideapad.330.-.Catalina.10.15.5.-.2020.zip)
你的这个貌似不可以用，我升级10.15.4卡代码。五国了
